'use client';

import { useEffect, useState } from 'react';
import LoadingSpinner from '@/components/LoadingSpinner';
import { downloadExport, downloadTextFile, fetchExports } from '@/lib/reportStudio';

const buttonClass = 'px-2.5 py-1.5 text-xs font-medium rounded-lg border transition-colors';
const inputClass = 'px-2.5 py-1.5 text-sm border border-gray-700/60 rounded-lg bg-gray-800/60 text-gray-200';

export default function ExportHistoryPage() {
  const [items, setItems] = useState<Record<string, unknown>[]>([]);
  const [search, setSearch] = useState('');
  const [format, setFormat] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true);
    try {
      const data = await fetchExports({ search: search || undefined, format: format || undefined });
      setItems(data.exports || []);
      setError('');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  return (
    <div className="space-y-4">
      {error && <div className="rounded-lg border border-red-800 bg-red-900/20 p-3 text-sm text-red-400">{error}</div>}

      <div className="flex flex-wrap gap-2">
        <input
          className={inputClass + ' flex-1 min-w-[180px]'}
          placeholder="Search by report name…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select className={inputClass} value={format} onChange={(e) => setFormat(e.target.value)}>
          <option value="">All formats</option>
          {['csv', 'json', 'pdf', 'xlsx', 'docx', 'print'].map((f) => (
            <option key={f} value={f}>
              {f.toUpperCase()}
            </option>
          ))}
        </select>
        <button type="button" onClick={load} className={`${buttonClass} border-amber-500/40 text-amber-300`}>
          Search
        </button>
      </div>

      {loading ? (
        <LoadingSpinner message="Loading export history…" />
      ) : (
        <div className="overflow-auto rounded-xl border border-gray-700/60">
          <table className="min-w-full text-xs">
            <thead className="bg-gray-900/80 text-gray-500">
              <tr>
                <th className="px-3 py-2 text-left font-medium">Report</th>
                <th className="px-3 py-2 text-left font-medium">Generated by</th>
                <th className="px-3 py-2 text-left font-medium">Generated on</th>
                <th className="px-3 py-2 text-left font-medium">Format</th>
                <th className="px-3 py-2 text-left font-medium">Records</th>
                <th className="px-3 py-2 text-left font-medium">Status</th>
                <th className="px-3 py-2 text-left font-medium">Download</th>
              </tr>
            </thead>
            <tbody>
              {items.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-3 py-6 text-center text-gray-500">
                    No exports yet.
                  </td>
                </tr>
              )}
              {items.map((row) => {
                const id = String(row._id);
                const user = row.generatedBy as { name?: string } | undefined;
                return (
                  <tr key={id} className="border-t border-gray-800 text-gray-300">
                    <td className="px-3 py-2">{String(row.reportName)}</td>
                    <td className="px-3 py-2">{user?.name || '—'}</td>
                    <td className="px-3 py-2 whitespace-nowrap">
                      {row.createdAt ? new Date(String(row.createdAt)).toLocaleString('en-IN') : '—'}
                    </td>
                    <td className="px-3 py-2 uppercase">{String(row.format)}</td>
                    <td className="px-3 py-2">{String(row.recordCount ?? 0)}</td>
                    <td className="px-3 py-2">{String(row.status)}</td>
                    <td className="px-3 py-2">
                      <button
                        type="button"
                        className={`${buttonClass} border-emerald-500/40 text-emerald-300`}
                        onClick={async () => {
                          try {
                            const file = await downloadExport(id);
                            downloadTextFile(file.fileName, file.content, file.contentType, file.encoding);
                          } catch (e) {
                            setError(e instanceof Error ? e.message : 'Download failed');
                          }
                        }}
                      >
                        Download again
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
