import Contact from '../../models/Contact.js';
import ImportJob from '../../models/ImportJob.js';
import ImportJobRow from '../../models/ImportJobRow.js';
import { EMPLOYEE_IMPORT_FIELDS } from './employeeImportCatalog.js';
import {
  allocateEmployeeIds,
  buildEmployeeIdPrefix,
  formatEmployeeId,
  getOrgNameForEmployeeIds,
  peekNextEmployeeIdSeq,
} from '../employeeIdService.js';

function str(v) {
  return v == null ? '' : String(v).trim();
}

function mapRow(raw, columnMappings) {
  const out = {};
  for (const m of columnMappings || []) {
    if (!m || m.ignored || !m.targetField) continue;
    out[m.targetField] = raw?.[m.sourceColumn];
  }
  return out;
}

/**
 * Validate mapped employee import rows.
 * When autoGenerateEmployeeIds is on, missing IDs get preview values (ORG-DEPT-####).
 */
export async function validateEmployeeImportJob(jobId, organizationId) {
  const job = await ImportJob.findOne({ _id: jobId, organizationId, module: 'employees' });
  if (!job) {
    const err = new Error('Import job not found');
    err.status = 404;
    throw err;
  }

  const autoGen = Boolean(job.autoGenerateEmployeeIds);
  const rows = await ImportJobRow.find({ jobId: job._id }).sort({ rowIndex: 1 });
  const required = EMPLOYEE_IMPORT_FIELDS.filter((f) => f.required).map((f) => f.key);
  const seenIds = new Map();
  let valid = 0;
  let errors = 0;
  let warnings = 0;

  const orgName = await getOrgNameForEmployeeIds(organizationId);
  let nextSeq = autoGen ? await peekNextEmployeeIdSeq(organizationId) : 1;

  for (const row of rows) {
    const mapped = mapRow(row.raw, job.columnMappings);
    const issues = [];
    let employeeId = str(mapped.employeeId);
    const name = str(mapped.name);
    const email = str(mapped.email).toLowerCase();
    const department = str(mapped.department);
    const team = str(mapped.team);
    let autoGenerated = false;

    for (const key of required) {
      if (!str(mapped[key])) {
        issues.push({ level: 'error', field: key, message: `${key} is required` });
      }
    }

    if (!employeeId) {
      if (autoGen) {
        employeeId = formatEmployeeId(orgName, { department, team }, nextSeq);
        nextSeq += 1;
        autoGenerated = true;
        const prefix = buildEmployeeIdPrefix(orgName, { department, team });
        issues.push({
          level: 'warning',
          field: 'employeeId',
          message: `Employee ID will be auto-generated as ${employeeId} (${prefix}-####)`,
        });
      } else {
        issues.push({
          level: 'error',
          field: 'employeeId',
          message: 'employeeId is required (or enable auto-generate employee IDs)',
        });
      }
    }

    if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      issues.push({ level: 'error', field: 'email', message: 'Invalid email' });
    }
    if (employeeId) {
      if (seenIds.has(employeeId)) {
        issues.push({
          level: 'error',
          field: 'employeeId',
          message: `Duplicate employeeId in file (also row ${seenIds.get(employeeId) + 1})`,
        });
      } else {
        seenIds.set(employeeId, row.rowIndex);
      }
    }

    let existing = employeeId
      ? await Contact.findOne({ organizationId, employeeId }).select('_id kind isActive').lean()
      : null;

    // Rows without a provided ID may still match an existing employee by email (update path).
    if (!existing && email && autoGenerated) {
      existing = await Contact.findOne({
        organizationId,
        kind: 'employee',
        email,
      })
        .select('_id kind isActive employeeId')
        .lean();
      if (existing?.employeeId) {
        employeeId = existing.employeeId;
        autoGenerated = false;
        issues.push({
          level: 'warning',
          field: 'email',
          message: `Matched existing employee ${existing.employeeId} by email — will update`,
        });
      }
    }

    if (existing && job.duplicateHandling === 'skip') {
      issues.push({ level: 'warning', field: 'employeeId', message: 'Already exists — will skip' });
    } else if (existing && job.duplicateHandling === 'update') {
      issues.push({ level: 'warning', field: 'employeeId', message: 'Already exists — will update' });
    } else if (existing && job.duplicateHandling === 'stop') {
      issues.push({ level: 'error', field: 'employeeId', message: 'Already exists — stop on duplicate' });
    }

    const hasError = issues.some((i) => i.level === 'error');
    const hasWarning = issues.some((i) => i.level === 'warning');
    row.mapped = {
      employeeId,
      name,
      email,
      phone: str(mapped.phone),
      department,
      team,
      autoGeneratedEmployeeId: autoGenerated ? '1' : '',
    };
    row.issues = issues.map((i) => ({
      severity: i.level === 'warning' ? 'warning' : 'error',
      field: i.field || '',
      message: i.message,
      level: i.level === 'warning' ? 'warning' : 'error',
    }));
    row.status = hasError ? 'error' : hasWarning ? 'warning' : 'valid';
    await row.save();

    if (hasError) errors += 1;
    else if (hasWarning) warnings += 1;
    else valid += 1;
  }

  job.validationSummary = { valid, warnings, errors };
  job.status = 'validated';
  job.wizardStep = 'preview';
  await job.save();

  return {
    job,
    summary: job.validationSummary,
  };
}

/**
 * Upsert employee contacts from a validated import job. Never creates Users.
 * Reserves continuing employee ID sequences for any still-missing / flagged auto IDs.
 */
export async function executeEmployeeImport(jobId, organizationId, userId) {
  const job = await ImportJob.findOne({ _id: jobId, organizationId, module: 'employees' });
  if (!job) {
    const err = new Error('Import job not found');
    err.status = 404;
    throw err;
  }

  job.status = 'importing';
  await job.save();

  const rows = await ImportJobRow.find({
    jobId: job._id,
    status: { $in: ['valid', 'warning'] },
  }).sort({ rowIndex: 1 });

  const needAlloc = [];
  for (const row of rows) {
    const m = row.mapped || {};
    const wantsAuto =
      Boolean(job.autoGenerateEmployeeIds) &&
      (m.autoGeneratedEmployeeId === '1' || !str(m.employeeId));
    if (wantsAuto) {
      // Prefer updating by email if already in roster — keep their existing ID.
      const email = str(m.email).toLowerCase();
      if (email) {
        const byEmail = await Contact.findOne({
          organizationId,
          kind: 'employee',
          email,
        })
          .select('employeeId')
          .lean();
        if (byEmail?.employeeId) {
          m.employeeId = byEmail.employeeId;
          m.autoGeneratedEmployeeId = '';
          row.mapped = m;
          continue;
        }
      }
      needAlloc.push(row);
    }
  }

  if (needAlloc.length) {
    const ids = await allocateEmployeeIds(
      organizationId,
      needAlloc.map((r) => ({
        department: str(r.mapped?.department),
        team: str(r.mapped?.team),
      }))
    );
    needAlloc.forEach((row, i) => {
      row.mapped = {
        ...(row.mapped || {}),
        employeeId: ids[i],
        autoGeneratedEmployeeId: '1',
      };
    });
  }

  let created = 0;
  let updated = 0;
  let skipped = 0;
  let failed = 0;

  for (const row of rows) {
    try {
      const m = row.mapped || {};
      const employeeId = str(m.employeeId);
      const name = str(m.name);
      const email = str(m.email).toLowerCase();
      if (!employeeId || !name || !email) {
        skipped += 1;
        row.status = 'skipped';
        await row.save();
        continue;
      }

      let existing = await Contact.findOne({ organizationId, employeeId });
      if (!existing && email) {
        existing = await Contact.findOne({ organizationId, kind: 'employee', email });
      }

      if (existing) {
        if (job.duplicateHandling === 'skip' || job.duplicateHandling === 'stop') {
          skipped += 1;
          row.status = 'skipped';
          await row.save();
          continue;
        }
        existing.kind = 'employee';
        existing.source = 'import';
        if (!existing.employeeId) existing.employeeId = employeeId;
        existing.name = name;
        existing.email = email;
        existing.phone = str(m.phone);
        existing.department = str(m.department);
        existing.team = str(m.team);
        existing.isActive = true;
        existing.updatedBy = userId;
        await existing.save();
        updated += 1;
        row.status = 'updated';
        row.mapped = { ...m, employeeId: existing.employeeId || employeeId };
        await row.save();
      } else {
        await Contact.create({
          organizationId,
          kind: 'employee',
          source: 'import',
          employeeId,
          name,
          email,
          phone: str(m.phone),
          department: str(m.department),
          team: str(m.team),
          isActive: true,
          createdBy: userId,
          updatedBy: userId,
        });
        created += 1;
        row.status = 'created';
        await row.save();
      }
    } catch (err) {
      failed += 1;
      row.status = 'failed';
      row.issues = [...(row.issues || []), { severity: 'error', level: 'error', message: err.message }];
      await row.save();
    }
  }

  job.result = { created, updated, skipped, failed };
  job.status = failed && !created && !updated ? 'failed' : 'completed';
  job.wizardStep = 'import';
  job.fileBuffer = undefined;
  await job.save();

  return { job, result: job.result };
}
