export function getDefaultBusinessPartnerOrgConfig() {
  return {
    partnerTypes: [
      { id: 'vendor', name: 'Vendor', description: 'General vendor', isDefault: true },
      { id: 'supplier', name: 'Supplier', description: '' },
      { id: 'manufacturer', name: 'Manufacturer', description: '' },
      { id: 'contractor', name: 'Contractor', description: '' },
      { id: 'service_provider', name: 'Service Provider', description: '' },
      { id: 'maintenance_partner', name: 'Maintenance Partner', description: '' },
      { id: 'rental_company', name: 'Rental Company', description: '' },
      { id: 'logistics_provider', name: 'Logistics Provider', description: '' },
      { id: 'consultant', name: 'Consultant', description: '' },
      { id: 'distributor', name: 'Distributor', description: '' },
      { id: 'oem', name: 'OEM', description: '' },
    ],
    categories: [
      { id: 'it', name: 'IT' },
      { id: 'furniture', name: 'Furniture' },
      { id: 'electrical', name: 'Electrical' },
      { id: 'hardware', name: 'Hardware' },
      { id: 'software', name: 'Software' },
      { id: 'services', name: 'Services' },
      { id: 'supplies', name: 'Supplies' },
      { id: 'other', name: 'Other', isDefault: true },
    ],
    statuses: [
      { id: 'Active', name: 'Active', color: '#10b981', isDefault: true },
      { id: 'Inactive', name: 'Inactive', color: '#6b7280' },
      { id: 'Blacklisted', name: 'Blacklisted', color: '#ef4444' },
      { id: 'Pending', name: 'Pending', color: '#f59e0b' },
    ],
    profileSections: [
      { key: 'general', label: 'General Information', enabled: true },
      { key: 'tax', label: 'Tax Information', enabled: true },
      { key: 'registration', label: 'Registration Details', enabled: true },
      { key: 'business', label: 'Business Details', enabled: true },
      { key: 'contacts', label: 'Contacts', enabled: true },
      { key: 'addresses', label: 'Addresses', enabled: true },
      { key: 'bank', label: 'Bank Details', enabled: true },
      { key: 'payment', label: 'Payment Terms', enabled: true },
      { key: 'custom', label: 'Custom Fields', enabled: true },
    ],
    addressTypes: [
      { id: 'registered', name: 'Registered Office' },
      { id: 'billing', name: 'Billing Address' },
      { id: 'shipping', name: 'Shipping Address' },
      { id: 'warehouse', name: 'Warehouse' },
      { id: 'branch', name: 'Branch Office' },
      { id: 'service_center', name: 'Service Center' },
    ],
    assetRelationshipTypes: [
      { key: 'purchased_from', label: 'Purchased From' },
      { key: 'maintained_by', label: 'Maintained By' },
      { key: 'installed_by', label: 'Installed By' },
      { key: 'manufactured_by', label: 'Manufactured By' },
      { key: 'disposed_through', label: 'Disposed Through' },
      { key: 'inspected_by', label: 'Inspected By' },
      { key: 'rental_provider', label: 'Rental Provider' },
    ],
    serviceRelationshipTypes: [
      { key: 'maintenance', label: 'Maintenance', resourceType: 'maintenance' },
      { key: 'work_order', label: 'Work Order', resourceType: 'work_order' },
      { key: 'audit', label: 'Audit', resourceType: 'audit' },
      { key: 'issue', label: 'Issue', resourceType: 'issue' },
      { key: 'inspection', label: 'Inspection', resourceType: 'inspection' },
      { key: 'project', label: 'Project', resourceType: 'project' },
      { key: 'budget', label: 'Budget', resourceType: 'budget' },
    ],
    customFields: [],
    performanceKpis: [
      { key: 'avg_delivery_time', label: 'Average Delivery Time', description: 'Mean delivery lead time', unit: 'days', higherIsBetter: false, isBuiltin: true },
      { key: 'avg_response_time', label: 'Average Response Time', description: 'Mean response time', unit: 'hours', higherIsBetter: false, isBuiltin: true },
      { key: 'issue_resolution_time', label: 'Issue Resolution Time', description: 'Mean time to resolve issues', unit: 'days', higherIsBetter: false, isBuiltin: true },
      { key: 'total_spend', label: 'Total Spend', description: 'Lifetime invoice spend', unit: 'currency', higherIsBetter: false, isBuiltin: true },
      { key: 'on_time_deliveries', label: 'On-time Deliveries', description: 'Share of on-time deliveries', unit: 'percent', higherIsBetter: true, isBuiltin: true },
      { key: 'failed_deliveries', label: 'Failed Deliveries', description: 'Count of failed deliveries', unit: 'count', higherIsBetter: false, isBuiltin: true },
      { key: 'repeat_purchases', label: 'Repeat Purchases', description: 'Number of purchases', unit: 'count', higherIsBetter: true, isBuiltin: true },
      { key: 'contract_renewals', label: 'Contract Renewals', description: 'Renewed contracts', unit: 'count', higherIsBetter: true, isBuiltin: true },
      { key: 'average_rating', label: 'Average Rating', description: 'Average partner rating', unit: 'score', higherIsBetter: true, isBuiltin: true },
    ],
    dashboardWidgetCatalog: [
      { key: 'total_partners', label: 'Total Partners', kind: 'metric' },
      { key: 'active_partners', label: 'Active Partners', kind: 'metric' },
      { key: 'inactive_partners', label: 'Inactive Partners', kind: 'metric' },
      { key: 'contracts_expiring', label: 'Contracts Expiring', kind: 'metric' },
      { key: 'pending_payments', label: 'Pending Payments', kind: 'metric' },
      { key: 'purchase_value', label: 'Total Purchase Value', kind: 'metric' },
      { key: 'linked_assets', label: 'Assets Linked', kind: 'metric' },
      { key: 'recent_activity', label: 'Recent Activity', kind: 'list' },
      { key: 'top_performers', label: 'Top Performing Partners', kind: 'list' },
    ],
    settings: {
      partnerCodePrefix: 'BP',
      defaultCurrency: 'INR',
      defaultPaymentTerms: 'Net 30',
    },
  };
}

export function getDefaultPartnerDashboardLayout() {
  return {
    version: 1,
    widgets: [
      { id: 'w1', title: 'Total Partners', kind: 'metric', metric: 'total_partners', order: 0, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w2', title: 'Active Partners', kind: 'metric', metric: 'active_partners', order: 1, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w3', title: 'Pending Payments', kind: 'metric', metric: 'pending_payments', order: 2, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w4', title: 'Purchase Value', kind: 'metric', metric: 'purchase_value', order: 3, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w5', title: 'Contracts Expiring', kind: 'metric', metric: 'contracts_expiring', order: 4, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w6', title: 'Assets Linked', kind: 'metric', metric: 'linked_assets', order: 5, colSpan: 1, rowSpan: 1, filters: {}, filterFields: [] },
      { id: 'w7', title: 'Recent Activity', kind: 'list', metric: 'recent_activity', order: 6, colSpan: 2, rowSpan: 2, filters: {}, filterFields: [] },
      { id: 'w8', title: 'Top Partners', kind: 'list', metric: 'top_performers', order: 7, colSpan: 2, rowSpan: 2, filters: {}, filterFields: [] },
    ],
  };
}
