/** Default organization thresholds — editable per org. */
export const DEFAULT_INSIGHT_THRESHOLDS = {
  budgetUtilizationWarning: 80,
  budgetUtilizationCritical: 95,
  warrantyAlertDays: 30,
  warrantyAlertDaysSecondary: 60,
  warrantyAlertDaysTertiary: 15,
  healthScoreWarning: 50,
  healthScoreCritical: 35,
  replacementScoreHigh: 80,
  replacementScoreCritical: 90,
  repairCountThreshold: 5,
  ageYearsThreshold: 6,
  maintenanceCostThreshold: 20000,
  openCriticalIssuesThreshold: 1,
  auditDueDays: 365,
  scanStaleDays: 90,
  maintenanceDueSoonDays: 14,
  highIssueCountThreshold: 3,
  lowUtilizationPct: 20,
};

export const INSIGHT_SEVERITIES = ['info', 'warning', 'critical'];
export const INSIGHT_CATEGORIES = [
  'warranty',
  'budget',
  'maintenance',
  'health',
  'audit',
  'assignment',
  'issues',
  'lifecycle',
  'custom',
];

export const INSIGHT_OPERATORS = [
  'eq',
  'ne',
  'gt',
  'gte',
  'lt',
  'lte',
  'contains',
  'in',
  'empty',
  'not_empty',
];

const cond = (metric, operator, value, thresholdKey = null) => ({
  metric,
  operator,
  value,
  ...(thresholdKey ? { thresholdKey } : {}),
});

/** 25 built-in insight rules shipped with Resolve. */
export function getDefaultInsightRules() {
  return [
    {
      ruleKey: 'warranty_expiring',
      name: 'Warranty Expiring',
      description: 'Assets with warranty expiring within the alert window',
      category: 'warranty',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have warranty expiring within {{days}} days',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('warrantyDaysUntilExpiry', 'lte', 30, 'warrantyAlertDays'),
              cond('warrantyDaysUntilExpiry', 'gt', 0),
            ],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 1,
    },
    {
      ruleKey: 'warranty_expired',
      name: 'Warranty Expired',
      description: 'Assets with expired warranty coverage',
      category: 'warranty',
      ruleType: 'asset',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have expired warranty',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('warrantyDaysUntilExpiry', 'lte', 0)] }],
      },
      link: '/dashboard/assets',
      order: 2,
    },
    {
      ruleKey: 'amc_expiring',
      name: 'AMC Expiring Soon',
      description: 'Assets with AMC expiring within alert window',
      category: 'warranty',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have AMC expiring within {{days}} days',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('amcDaysUntilExpiry', 'lte', 30, 'warrantyAlertDays'),
              cond('amcDaysUntilExpiry', 'gt', 0),
            ],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 3,
    },
    {
      ruleKey: 'budget_utilization_warning',
      name: 'Budget Utilization Warning',
      description: 'Budgets approaching utilization threshold',
      category: 'budget',
      ruleType: 'budget',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} budget(s) are above {{pct}}% utilization',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('utilizationPct', 'gte', 80, 'budgetUtilizationWarning'),
              cond('utilizationPct', 'lt', 95, 'budgetUtilizationCritical'),
            ],
          },
        ],
      },
      link: '/dashboard/budgets',
      order: 4,
    },
    {
      ruleKey: 'budget_utilization_critical',
      name: 'Budget Near Limit',
      description: 'Budgets at critical utilization level',
      category: 'budget',
      ruleType: 'budget',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} budget(s) are at or above {{pct}}% utilization',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('utilizationPct', 'gte', 95, 'budgetUtilizationCritical')],
          },
        ],
      },
      link: '/dashboard/budgets',
      order: 5,
    },
    {
      ruleKey: 'budget_exceeded',
      name: 'Budget Exceeded',
      description: 'Budgets that have exceeded allocated amount',
      category: 'budget',
      ruleType: 'budget',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} budget(s) have exceeded their allocation',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('utilizationPct', 'gte', 100)] }],
      },
      link: '/dashboard/budgets',
      order: 6,
    },
    {
      ruleKey: 'high_maintenance_cost',
      name: 'High Maintenance Cost',
      description: 'Assets with maintenance spend above threshold',
      category: 'maintenance',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) exceed maintenance cost threshold',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('maintenanceCost', 'gt', 20000, 'maintenanceCostThreshold')],
          },
        ],
      },
      link: '/dashboard/maintenance',
      order: 7,
    },
    {
      ruleKey: 'frequent_repairs',
      name: 'Frequent Repairs',
      description: 'Assets with high repair / maintenance event count',
      category: 'maintenance',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have more than {{threshold}} repair events',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('repairCount', 'gt', 5, 'repairCountThreshold')],
          },
        ],
      },
      link: '/dashboard/maintenance',
      order: 8,
    },
    {
      ruleKey: 'overdue_maintenance',
      name: 'Overdue Maintenance',
      description: 'Assets past scheduled maintenance date',
      category: 'maintenance',
      ruleType: 'asset',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have overdue maintenance',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('daysUntilMaintenance', 'lt', 0)] }],
      },
      link: '/dashboard/maintenance',
      order: 9,
    },
    {
      ruleKey: 'maintenance_due_soon',
      name: 'Maintenance Due Soon',
      description: 'Assets with maintenance due within alert window',
      category: 'maintenance',
      ruleType: 'asset',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} asset(s) need maintenance within {{days}} days',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('daysUntilMaintenance', 'gte', 0),
              cond('daysUntilMaintenance', 'lte', 14, 'maintenanceDueSoonDays'),
            ],
          },
        ],
      },
      link: '/dashboard/maintenance',
      order: 10,
    },
    {
      ruleKey: 'assets_not_audited',
      name: 'Assets Not Audited',
      description: 'Assets not verified within audit period',
      category: 'audit',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have not been audited in {{days}} days',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('daysSinceLastAudit', 'gt', 365, 'auditDueDays')],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 11,
    },
    {
      ruleKey: 'assets_not_scanned',
      name: 'Assets Not Scanned Recently',
      description: 'Assets without recent check-in or activity',
      category: 'audit',
      ruleType: 'asset',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have not been scanned in {{days}} days',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('daysSinceLastScan', 'gt', 90, 'scanStaleDays')],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 12,
    },
    {
      ruleKey: 'low_health_score',
      name: 'Low Health Score',
      description: 'Assets below health score warning threshold',
      category: 'health',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have health score below {{threshold}}',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('healthScore', 'lt', 50, 'healthScoreWarning')],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 13,
    },
    {
      ruleKey: 'critical_health_score',
      name: 'Critical Health Score',
      description: 'Assets in critical health condition',
      category: 'health',
      ruleType: 'asset',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have critically low health scores',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('healthScore', 'lt', 35, 'healthScoreCritical')],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 14,
    },
    {
      ruleKey: 'high_replacement_score',
      name: 'High Replacement Score',
      description: 'Assets with high replacement priority score',
      category: 'health',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have replacement score above {{threshold}}',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('replacementScore', 'gt', 80, 'replacementScoreHigh')],
          },
        ],
      },
      link: '/dashboard/depreciation',
      order: 15,
    },
    {
      ruleKey: 'replacement_recommendation',
      name: 'Replacement Recommendation',
      description: 'Assets recommended for replacement based on health, score, repairs, and age',
      category: 'health',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) are recommended for replacement',
      conditionTree: {
        rootLogic: 'or',
        groups: [
          {
            logic: 'and',
            conditions: [cond('healthScore', 'lt', 40, 'healthScoreCritical')],
          },
          {
            logic: 'and',
            conditions: [cond('replacementScore', 'gt', 80, 'replacementScoreHigh')],
          },
          {
            logic: 'and',
            conditions: [
              cond('repairCount', 'gt', 5, 'repairCountThreshold'),
              cond('ageYears', 'gt', 6, 'ageYearsThreshold'),
            ],
          },
        ],
      },
      link: '/dashboard/depreciation',
      order: 16,
    },
    {
      ruleKey: 'open_critical_issues',
      name: 'Open Critical Issues',
      description: 'Assets with open critical-severity issues',
      category: 'issues',
      ruleType: 'asset',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have open critical issues',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('openCriticalIssueCount', 'gte', 1, 'openCriticalIssuesThreshold')],
          },
        ],
      },
      link: '/dashboard/issues',
      order: 17,
    },
    {
      ruleKey: 'high_issue_count',
      name: 'High Issue Count',
      description: 'Assets with many reported issues',
      category: 'issues',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have more than {{threshold}} open issues',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('openIssueCount', 'gt', 3, 'highIssueCountThreshold')],
          },
        ],
      },
      link: '/dashboard/issues',
      order: 18,
    },
    {
      ruleKey: 'assets_unassigned',
      name: 'Assets Unassigned',
      description: 'Active assets without an assignee',
      category: 'assignment',
      ruleType: 'asset',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} active asset(s) are unassigned',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('isAssigned', 'eq', 0),
              cond('isActive', 'eq', 1),
            ],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 19,
    },
    {
      ruleKey: 'under_maintenance',
      name: 'Assets Under Maintenance',
      description: 'Assets currently in maintenance status',
      category: 'lifecycle',
      ruleType: 'asset',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} asset(s) are currently under maintenance',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('status', 'eq', 'under_maintenance')] }],
      },
      link: '/dashboard/maintenance',
      order: 20,
    },
    {
      ruleKey: 'needs_repair',
      name: 'Assets Needing Repair',
      description: 'Assets flagged as needing repair',
      category: 'lifecycle',
      ruleType: 'asset',
      severity: 'warning',
      enabled: true,
      messageTemplate: '{{count}} asset(s) need repair',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('status', 'eq', 'needs_repair')] }],
      },
      link: '/dashboard/assets',
      order: 21,
    },
    {
      ruleKey: 'old_assets',
      name: 'Aging Assets',
      description: 'Assets older than threshold years',
      category: 'lifecycle',
      ruleType: 'asset',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} asset(s) are older than {{threshold}} years',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('ageYears', 'gt', 6, 'ageYearsThreshold')],
          },
        ],
      },
      link: '/dashboard/assets',
      order: 22,
    },
    {
      ruleKey: 'low_utilization',
      name: 'Low Utilization',
      description: 'Assigned assets with low utilization',
      category: 'lifecycle',
      ruleType: 'asset',
      severity: 'info',
      enabled: false,
      messageTemplate: '{{count}} asset(s) have low utilization',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [
              cond('isAssigned', 'eq', 1),
              cond('utilization', 'lt', 20, 'lowUtilizationPct'),
            ],
          },
        ],
      },
      link: '/dashboard/kpis',
      order: 23,
    },
    {
      ruleKey: 'pending_procurement',
      name: 'Pending Purchase Requests',
      description: 'Procurement requests awaiting completion',
      category: 'budget',
      ruleType: 'aggregate',
      severity: 'info',
      enabled: true,
      messageTemplate: '{{count}} purchase request(s) are pending',
      conditionTree: {
        rootLogic: 'and',
        groups: [
          {
            logic: 'and',
            conditions: [cond('pendingProcurementCount', 'gt', 0)],
          },
        ],
      },
      link: '/dashboard/budgets/procurement',
      order: 24,
    },
    {
      ruleKey: 'replacement_priority_critical',
      name: 'Critical Replacement Priority',
      description: 'Assets with critical replacement priority',
      category: 'health',
      ruleType: 'asset',
      severity: 'critical',
      enabled: true,
      messageTemplate: '{{count}} asset(s) have critical replacement priority',
      conditionTree: {
        rootLogic: 'and',
        groups: [{ logic: 'and', conditions: [cond('replacementPriority', 'eq', 'critical')] }],
      },
      link: '/dashboard/depreciation',
      order: 25,
    },
  ];
}

export const INSIGHT_METRIC_CATALOG = [
  { key: 'healthScore', label: 'Health Score', type: 'number', scope: 'asset' },
  { key: 'replacementScore', label: 'Replacement Score', type: 'number', scope: 'asset' },
  { key: 'replacementPriority', label: 'Replacement Priority', type: 'select', scope: 'asset', options: ['low', 'medium', 'high', 'critical'] },
  { key: 'ageYears', label: 'Asset Age (years)', type: 'number', scope: 'asset' },
  { key: 'repairCount', label: 'Repair Count', type: 'number', scope: 'asset' },
  { key: 'maintenanceCost', label: 'Maintenance Cost', type: 'currency', scope: 'asset' },
  { key: 'openIssueCount', label: 'Open Issues', type: 'number', scope: 'asset' },
  { key: 'openCriticalIssueCount', label: 'Open Critical Issues', type: 'number', scope: 'asset' },
  { key: 'warrantyDaysUntilExpiry', label: 'Days Until Warranty Expiry', type: 'number', scope: 'asset' },
  { key: 'amcDaysUntilExpiry', label: 'Days Until AMC Expiry', type: 'number', scope: 'asset' },
  { key: 'daysUntilMaintenance', label: 'Days Until Maintenance', type: 'number', scope: 'asset' },
  { key: 'daysSinceLastAudit', label: 'Days Since Last Audit', type: 'number', scope: 'asset' },
  { key: 'daysSinceLastScan', label: 'Days Since Last Scan', type: 'number', scope: 'asset' },
  { key: 'utilization', label: 'Utilization %', type: 'number', scope: 'asset' },
  { key: 'isAssigned', label: 'Is Assigned', type: 'boolean', scope: 'asset' },
  { key: 'isActive', label: 'Is Active', type: 'boolean', scope: 'asset' },
  { key: 'status', label: 'Status', type: 'select', scope: 'asset', options: ['available', 'in_use', 'under_maintenance', 'retired', 'working', 'needs_repair', 'out_of_service'] },
  { key: 'departmentId', label: 'Department', type: 'reference', scope: 'asset', ref: 'department' },
  { key: 'locationId', label: 'Location', type: 'reference', scope: 'asset', ref: 'location' },
  { key: 'category', label: 'Category', type: 'text', scope: 'asset' },
  { key: 'assetCost', label: 'Asset Cost', type: 'currency', scope: 'asset' },
  { key: 'utilizationPct', label: 'Budget Utilization %', type: 'number', scope: 'budget' },
  { key: 'pendingProcurementCount', label: 'Pending Purchases', type: 'number', scope: 'org' },
];
