/** Report Studio — operators, visualizations, and system quick-report presets. */

export const REPORT_OPERATORS = [
  { key: 'eq', label: 'Equals', types: ['string', 'number', 'date', 'boolean', 'select'] },
  { key: 'neq', label: 'Not equals', types: ['string', 'number', 'date', 'boolean', 'select'] },
  { key: 'contains', label: 'Contains', types: ['string'] },
  { key: 'search', label: 'Search (fuzzy)', types: ['string', 'select'] },
  { key: 'starts_with', label: 'Starts with', types: ['string'] },
  { key: 'ends_with', label: 'Ends with', types: ['string'] },
  { key: 'gt', label: 'Greater than', types: ['number', 'date'] },
  { key: 'gte', label: 'Greater or equal', types: ['number', 'date'] },
  { key: 'lt', label: 'Less than', types: ['number', 'date'] },
  { key: 'lte', label: 'Less or equal', types: ['number', 'date'] },
  { key: 'between', label: 'Between', types: ['number', 'date'] },
  { key: 'in', label: 'In', types: ['string', 'number', 'select'] },
  { key: 'is_empty', label: 'Is empty', types: ['string', 'number', 'date', 'select'] },
  { key: 'is_not_empty', label: 'Is not empty', types: ['string', 'number', 'date', 'select'] },
];

export const REPORT_CALCULATION_TYPES = [
  { key: 'count', label: 'Count' },
  { key: 'sum', label: 'Sum' },
  { key: 'avg', label: 'Average' },
  { key: 'min', label: 'Minimum' },
  { key: 'max', label: 'Maximum' },
  { key: 'median', label: 'Median' },
  { key: 'distinct', label: 'Distinct count' },
  { key: 'percentage', label: 'Percentage' },
  { key: 'running_total', label: 'Running total' },
];

export const REPORT_VISUALIZATIONS = [
  { key: 'table', label: 'Table' },
  { key: 'pivot', label: 'Pivot table' },
  { key: 'kpi', label: 'KPI cards' },
  { key: 'bar', label: 'Bar chart' },
  { key: 'line', label: 'Line chart' },
  { key: 'pie', label: 'Pie chart' },
  { key: 'donut', label: 'Donut chart' },
  { key: 'area', label: 'Area chart' },
  { key: 'heatmap', label: 'Heatmap' },
  { key: 'treemap', label: 'Treemap' },
  { key: 'timeline', label: 'Timeline' },
];

export const REPORT_EXPORT_FORMATS = ['pdf', 'xlsx', 'csv', 'docx', 'json', 'print'];

export const REPORT_DATA_SOURCES = [
  { key: 'assets', label: 'Assets', description: 'Asset register and custom fields' },
  { key: 'issues', label: 'Issues', description: 'Tickets and issue reports' },
  { key: 'maintenance', label: 'Maintenance', description: 'Assets under maintenance / history' },
  { key: 'vendors', label: 'Vendors', description: 'Vendor directory' },
  { key: 'locations', label: 'Locations', description: 'Location hierarchy' },
  { key: 'users', label: 'Users', description: 'Organization users' },
  { key: 'audits', label: 'Audits', description: 'Audit trail events' },
  { key: 'budgets', label: 'Budgets', description: 'Budgets and custom budget fields' },
  { key: 'procurement', label: 'Purchase orders', description: 'Procurement / purchase records' },
  { key: 'invoices', label: 'Invoices', description: 'Vendor invoices' },
];

/** Built-in fields per source. Custom fields are merged at runtime. */
export const BUILTIN_FIELDS = {
  assets: [
    { key: 'assetId', label: 'Asset ID', type: 'string', groupable: true },
    { key: 'name', label: 'Asset name', type: 'string', groupable: true },
    { key: 'category', label: 'Category', type: 'string', groupable: true },
    { key: 'model', label: 'Model', type: 'string', groupable: true },
    { key: 'serialNumber', label: 'Serial number', type: 'string' },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'condition', label: 'Condition', type: 'select', groupable: true },
    { key: 'purchaseDate', label: 'Purchase date', type: 'date', groupable: true },
    { key: 'cost', label: 'Purchase cost', type: 'number', aggregatable: true },
    { key: 'vendor', label: 'Vendor (text)', type: 'string', groupable: true },
    { key: 'warrantyExpiry', label: 'Warranty expiry', type: 'date' },
    { key: 'amcExpiry', label: 'AMC expiry', type: 'date' },
    { key: 'nextMaintenanceDate', label: 'Next maintenance', type: 'date' },
    { key: 'assignedToName', label: 'Assigned name', type: 'string', groupable: true },
    { key: 'assignedToEmployeeCode', label: 'Employee code', type: 'string' },
    { key: 'locationName', label: 'Location', type: 'string', groupable: true, virtual: true },
    { key: 'departmentName', label: 'Department', type: 'string', groupable: true, virtual: true },
    { key: 'vendorName', label: 'Vendor', type: 'string', groupable: true, virtual: true },
    { key: 'assignedUserName', label: 'Assigned user', type: 'string', groupable: true, virtual: true },
    { key: 'maintenanceReason', label: 'Maintenance reason', type: 'string' },
    { key: 'maintenanceStartDate', label: 'Maintenance started', type: 'date' },
    { key: 'createdAt', label: 'Created', type: 'date', groupable: true },
    { key: 'updatedAt', label: 'Updated', type: 'date' },
  ],
  issues: [
    { key: 'ticketId', label: 'Ticket ID', type: 'string' },
    { key: 'title', label: 'Title', type: 'string' },
    { key: 'category', label: 'Category', type: 'string', groupable: true },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'priority', label: 'Priority', type: 'select', groupable: true },
    { key: 'reporterName', label: 'Reporter', type: 'string', groupable: true },
    { key: 'assetName', label: 'Asset', type: 'string', groupable: true, virtual: true },
    { key: 'assetTag', label: 'Asset ID', type: 'string', virtual: true },
    { key: 'locationName', label: 'Location', type: 'string', groupable: true, virtual: true },
    { key: 'createdAt', label: 'Created', type: 'date', groupable: true },
    { key: 'updatedAt', label: 'Updated', type: 'date' },
  ],
  maintenance: [
    { key: 'assetId', label: 'Asset ID', type: 'string' },
    { key: 'name', label: 'Asset name', type: 'string' },
    { key: 'category', label: 'Category', type: 'string', groupable: true },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'maintenanceReason', label: 'Reason', type: 'string' },
    { key: 'maintenanceStartDate', label: 'Started', type: 'date' },
    { key: 'maintenanceCompletedDate', label: 'Completed', type: 'date' },
    { key: 'locationName', label: 'Location', type: 'string', groupable: true, virtual: true },
    { key: 'departmentName', label: 'Department', type: 'string', groupable: true, virtual: true },
    { key: 'daysUnderMaintenance', label: 'Days open', type: 'number', aggregatable: true, virtual: true },
  ],
  vendors: [
    { key: 'vendorId', label: 'Vendor ID', type: 'string' },
    { key: 'name', label: 'Name', type: 'string', groupable: true },
    { key: 'email', label: 'Email', type: 'string' },
    { key: 'phone', label: 'Phone', type: 'string' },
    { key: 'category', label: 'Category', type: 'string', groupable: true },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
  locations: [
    { key: 'name', label: 'Name', type: 'string', groupable: true },
    { key: 'path', label: 'Path', type: 'string' },
    { key: 'type', label: 'Type', type: 'string', groupable: true },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
  users: [
    { key: 'name', label: 'Name', type: 'string', groupable: true },
    { key: 'email', label: 'Email', type: 'string' },
    { key: 'role', label: 'Role', type: 'select', groupable: true },
    { key: 'isActive', label: 'Active', type: 'boolean', groupable: true },
    { key: 'lastLogin', label: 'Last login', type: 'date' },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
  audits: [
    { key: 'action', label: 'Action', type: 'string', groupable: true },
    { key: 'resource', label: 'Resource', type: 'string', groupable: true },
    { key: 'resourceName', label: 'Resource name', type: 'string' },
    { key: 'description', label: 'Description', type: 'string' },
    { key: 'severity', label: 'Severity', type: 'select', groupable: true },
    { key: 'userName', label: 'User', type: 'string', groupable: true, virtual: true },
    { key: 'createdAt', label: 'When', type: 'date', groupable: true },
  ],
  budgets: [
    { key: 'name', label: 'Name', type: 'string' },
    { key: 'code', label: 'Code', type: 'string' },
    { key: 'budgetTypeId', label: 'Type', type: 'select', groupable: true },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'allocatedAmount', label: 'Allocated', type: 'number', aggregatable: true },
    { key: 'actualSpend', label: 'Spent', type: 'number', aggregatable: true },
    { key: 'remaining', label: 'Remaining', type: 'number', aggregatable: true, virtual: true },
    { key: 'financialYear', label: 'Fiscal year', type: 'string', groupable: true },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
  procurement: [
    { key: 'purchaseId', label: 'Purchase ID', type: 'string' },
    { key: 'purchaseOrderNumber', label: 'PO number', type: 'string' },
    { key: 'lifecycleStage', label: 'Lifecycle', type: 'select', groupable: true },
    { key: 'paymentStatus', label: 'Payment status', type: 'select', groupable: true },
    { key: 'amount', label: 'Amount', type: 'number', aggregatable: true },
    { key: 'totalCost', label: 'Total cost', type: 'number', aggregatable: true },
    { key: 'vendorName', label: 'Vendor', type: 'string', groupable: true, virtual: true },
    { key: 'purchaseDate', label: 'Purchase date', type: 'date', groupable: true },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
  invoices: [
    { key: 'invoiceNumber', label: 'Invoice #', type: 'string' },
    { key: 'totalAmount', label: 'Amount', type: 'number', aggregatable: true },
    { key: 'paidAmount', label: 'Paid', type: 'number', aggregatable: true },
    { key: 'status', label: 'Status', type: 'select', groupable: true },
    { key: 'vendorName', label: 'Vendor', type: 'string', groupable: true, virtual: true },
    { key: 'purchaseDate', label: 'Invoice date', type: 'date', groupable: true },
    { key: 'createdAt', label: 'Created', type: 'date' },
  ],
};

function fieldRefs(source, keys) {
  return keys.map((key, order) => ({ source, key, order }));
}

/** System quick reports — configs resolved against catalog at runtime. */
export const SYSTEM_QUICK_REPORTS = [
  {
    key: 'asset_register',
    name: 'Asset Register',
    category: 'Assets',
    description: 'Full asset register with location and assignment',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'category', 'status', 'locationName', 'departmentName', 'assignedToName', 'purchaseDate', 'cost']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'assets', key: 'assetId', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'asset_inventory',
    name: 'Asset Inventory',
    category: 'Assets',
    description: 'Inventory by category and status',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['category', 'status', 'name', 'assetId', 'locationName']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [{ source: 'assets', key: 'category' }],
      sort: [{ source: 'assets', key: 'category', dir: 'asc' }],
      calculations: [{ id: 'c1', type: 'count', field: 'assetId', label: 'Count' }],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'asset_assignment',
    name: 'Asset Assignment',
    category: 'Assets',
    description: 'Assets with assigned users',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'assignedToName', 'assignedToEmployeeCode', 'assignedUserName', 'departmentName', 'status']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'assignedToName', op: 'is_not_empty' }],
      },
      groupBy: [],
      sort: [{ source: 'assets', key: 'assignedToName', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'asset_lifecycle',
    name: 'Asset Lifecycle',
    category: 'Assets',
    description: 'Purchase, warranty, and maintenance dates',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'purchaseDate', 'warrantyExpiry', 'amcExpiry', 'nextMaintenanceDate', 'status', 'condition']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'assets', key: 'purchaseDate', dir: 'desc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'asset_status',
    name: 'Asset Status',
    category: 'Assets',
    description: 'Assets grouped by status',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['status', 'assetId', 'name', 'category', 'locationName']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [{ source: 'assets', key: 'status' }],
      sort: [{ source: 'assets', key: 'status', dir: 'asc' }],
      calculations: [{ id: 'c1', type: 'count', field: 'assetId', label: 'Count' }],
      visualization: { type: 'bar' },
      formatting: {},
    },
  },
  {
    key: 'warranty_report',
    name: 'Warranty Report',
    category: 'Assets',
    description: 'Assets with warranty expiry dates',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'warrantyExpiry', 'amcExpiry', 'vendorName', 'status']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'warrantyExpiry', op: 'is_not_empty' }],
      },
      groupBy: [],
      sort: [{ source: 'assets', key: 'warrantyExpiry', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'asset_utilization',
    name: 'Asset Utilization',
    category: 'Assets',
    description: 'In-use vs available assets',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['status', 'category', 'assetId', 'name', 'assignedToName']),
      filters: {
        logic: 'or',
        conditions: [
          { source: 'assets', field: 'status', op: 'eq', value: 'in_use' },
          { source: 'assets', field: 'status', op: 'eq', value: 'available' },
        ],
      },
      groupBy: [{ source: 'assets', key: 'status' }],
      sort: [],
      calculations: [{ id: 'c1', type: 'count', field: 'assetId', label: 'Count' }],
      visualization: { type: 'pie' },
      formatting: {},
    },
  },
  {
    key: 'upcoming_maintenance',
    name: 'Upcoming Maintenance',
    category: 'Maintenance',
    description: 'Assets with upcoming next-maintenance dates',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'nextMaintenanceDate', 'status', 'locationName']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'nextMaintenanceDate', op: 'is_not_empty' }],
      },
      groupBy: [],
      sort: [{ source: 'assets', key: 'nextMaintenanceDate', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'overdue_maintenance',
    name: 'Overdue Maintenance',
    category: 'Maintenance',
    description: 'Assets currently under maintenance',
    config: {
      primarySource: 'maintenance',
      dataSources: ['maintenance'],
      fields: fieldRefs('maintenance', ['assetId', 'name', 'maintenanceReason', 'maintenanceStartDate', 'daysUnderMaintenance', 'locationName']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'maintenance', key: 'maintenanceStartDate', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'maintenance_history',
    name: 'Maintenance History',
    category: 'Maintenance',
    description: 'Assets with completed maintenance dates',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'maintenanceCompletedDate', 'maintenanceReason', 'status']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'maintenanceCompletedDate', op: 'is_not_empty' }],
      },
      groupBy: [],
      sort: [{ source: 'assets', key: 'maintenanceCompletedDate', dir: 'desc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'audit_trail',
    name: 'Audit Trail',
    category: 'Audit',
    description: 'Recent audit log events',
    config: {
      primarySource: 'audits',
      dataSources: ['audits'],
      fields: fieldRefs('audits', ['createdAt', 'userName', 'action', 'resource', 'resourceName', 'description', 'severity']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'audits', key: 'createdAt', dir: 'desc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'audit_summary',
    name: 'Audit Summary',
    category: 'Audit',
    description: 'Audit events grouped by action',
    config: {
      primarySource: 'audits',
      dataSources: ['audits'],
      fields: fieldRefs('audits', ['action', 'resource', 'severity', 'userName', 'createdAt']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [{ source: 'audits', key: 'action' }],
      sort: [],
      calculations: [{ id: 'c1', type: 'count', field: 'action', label: 'Count' }],
      visualization: { type: 'bar' },
      formatting: {},
    },
  },
  {
    key: 'purchase_cost',
    name: 'Purchase Cost',
    category: 'Finance',
    description: 'Asset purchase costs',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assetId', 'name', 'category', 'purchaseDate', 'cost', 'vendorName']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'cost', op: 'is_not_empty' }],
      },
      groupBy: [],
      sort: [{ source: 'assets', key: 'cost', dir: 'desc' }],
      calculations: [{ id: 'c1', type: 'sum', field: 'cost', label: 'Total cost' }],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'vendor_spend',
    name: 'Vendor Spend',
    category: 'Finance',
    description: 'Invoice amounts by vendor',
    config: {
      primarySource: 'invoices',
      dataSources: ['invoices'],
      fields: fieldRefs('invoices', ['vendorName', 'invoiceNumber', 'totalAmount', 'status', 'purchaseDate']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [{ source: 'invoices', key: 'vendorName' }],
      sort: [{ source: 'invoices', key: 'totalAmount', dir: 'desc' }],
      calculations: [{ id: 'c1', type: 'sum', field: 'totalAmount', label: 'Total' }],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'budget_utilization',
    name: 'Budget Utilization',
    category: 'Finance',
    description: 'Budget amounts, spent, and remaining',
    config: {
      primarySource: 'budgets',
      dataSources: ['budgets'],
      fields: fieldRefs('budgets', ['name', 'code', 'budgetTypeId', 'status', 'allocatedAmount', 'actualSpend', 'remaining', 'financialYear']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'budgets', key: 'name', dir: 'asc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'user_activity',
    name: 'User Activity',
    category: 'Users',
    description: 'Users and last login',
    config: {
      primarySource: 'users',
      dataSources: ['users'],
      fields: fieldRefs('users', ['name', 'email', 'role', 'isActive', 'lastLogin', 'createdAt']),
      filters: { logic: 'and', conditions: [] },
      groupBy: [],
      sort: [{ source: 'users', key: 'lastLogin', dir: 'desc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'assigned_assets_by_user',
    name: 'Assigned Assets',
    category: 'Users',
    description: 'Assets grouped by assignee',
    config: {
      primarySource: 'assets',
      dataSources: ['assets'],
      fields: fieldRefs('assets', ['assignedToName', 'assetId', 'name', 'status', 'departmentName']),
      filters: {
        logic: 'and',
        conditions: [{ source: 'assets', field: 'assignedToName', op: 'is_not_empty' }],
      },
      groupBy: [{ source: 'assets', key: 'assignedToName' }],
      sort: [{ source: 'assets', key: 'assignedToName', dir: 'asc' }],
      calculations: [{ id: 'c1', type: 'count', field: 'assetId', label: 'Count' }],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
  {
    key: 'login_history',
    name: 'Login History',
    category: 'Users',
    description: 'Login success/failure from audit logs',
    config: {
      primarySource: 'audits',
      dataSources: ['audits'],
      fields: fieldRefs('audits', ['createdAt', 'userName', 'action', 'description', 'severity']),
      filters: {
        logic: 'or',
        conditions: [
          { source: 'audits', field: 'action', op: 'eq', value: 'login_success' },
          { source: 'audits', field: 'action', op: 'eq', value: 'login_failed' },
        ],
      },
      groupBy: [],
      sort: [{ source: 'audits', key: 'createdAt', dir: 'desc' }],
      calculations: [],
      visualization: { type: 'table' },
      formatting: {},
    },
  },
];

export const DEFAULT_REPORT_FORMATTING = {
  orientation: 'landscape',
  paperSize: 'a4',
  theme: 'default',
  dateFormat: 'dd MMM yyyy',
  currencyFormat: 'INR',
  decimalPrecision: 2,
  showLogo: true,
  header: '',
  footer: '',
  watermark: '',
};

export const DEFAULT_REPORT_STUDIO_SETTINGS = {
  defaultExportFormat: 'csv',
  timezone: 'Asia/Kolkata',
  currency: 'INR',
  defaultFilenameFormat: '{reportName}_{date}',
  retentionDays: 90,
  branding: {
    logoUrl: '',
    primaryColor: '#f59e0b',
    companyName: '',
  },
};
