export const AUDIT_RESOURCE_LABELS: Record<string, string> = {
  asset: 'Asset',
  issue: 'Issue',
  user: 'User',
  organization: 'Org',
  profile: 'Profile',
  location: 'Location',
  department: 'Department',
  authentication: 'Auth',
  vendor: 'Vendor',
  invoice: 'Invoice',
  report: 'Report',
  maintenance: 'Maintenance',
  audit: 'Audit',
  budget: 'Budget',
  procurement: 'Procurement',
  insight: 'Insights',
  asset_health: 'Asset Health',
};

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  created: 'Created',
  updated: 'Updated',
  deleted: 'Deleted',
  assigned: 'Assigned',
  unassigned: 'Unassigned',
  status_changed: 'Status Changed',
  role_changed: 'Role Changed',
  activated: 'Activated',
  deactivated: 'Deactivated',
  login_success: 'Login',
  login_failed: 'Login Failed',
  logout: 'Logout',
  generated: 'Generated',
  downloaded: 'Downloaded',
  password_changed: 'Password Changed',
  '2fa_enabled': '2FA Enabled',
  '2fa_disabled': '2FA Disabled',
  recovery_codes_regenerated: 'Recovery Codes Regenerated',
  maintenance_started: 'Maint. Started',
  maintenance_completed: 'Maint. Completed',
  note_added: 'Note Added',
  settings_changed: 'Settings Changed',
  reset: 'Reset',
  linked: 'Linked',
  duplicated: 'Duplicated',
  health_check_run: 'Health Check',
};

export const AUDIT_RESOURCE_ICONS: Record<string, string> = {
  asset: '📦',
  issue: '🔴',
  user: '👤',
  profile: '🛡️',
  organization: '🏢',
  location: '📍',
  department: '🏛️',
  authentication: '🔐',
  vendor: '🏪',
  invoice: '🧾',
  report: '📊',
  maintenance: '🔧',
  audit: '📋',
  budget: '💰',
  procurement: '🛒',
  insight: '💡',
  asset_health: '❤️',
};

export const AUDIT_ACTION_COLORS: Record<string, string> = {
  created: 'text-green-400',
  deleted: 'text-red-400',
  updated: 'text-blue-400',
  status_changed: 'text-amber-400',
  generated: 'text-purple-400',
  downloaded: 'text-teal-400',
  password_changed: 'text-amber-400',
  '2fa_enabled': 'text-emerald-400',
  '2fa_disabled': 'text-orange-400',
  recovery_codes_regenerated: 'text-violet-400',
  maintenance_started: 'text-orange-400',
  maintenance_completed: 'text-green-400',
  login_success: 'text-gray-400',
  login_failed: 'text-red-400',
  settings_changed: 'text-cyan-400',
  reset: 'text-violet-400',
  linked: 'text-blue-300',
  duplicated: 'text-indigo-400',
  health_check_run: 'text-emerald-300',
  note_added: 'text-gray-300',
};
